# Generated by Django 5.2.9 on 2026-01-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousprofile',
            name='last_active',
        ),
    ]
