# Generated by Django 5.2.10 on 2026-02-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_anonymousprofile_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousprofile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymousprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
