# Generated by Django 5.2.9 on 2026-01-03 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Board', max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('secret_admin_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('creator_ghost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='identity.anonymousprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('colour', models.CharField(choices=[('YELLOW', 'Yellow'), ('CREATIVE', 'Creative'), ('COOL', 'Cool'), ('FRESH', 'Fresh'), ('ROYAL', 'Royal')], default='YELLOW', max_length=20)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('is_anonymous_to_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workspace.board')),
                ('creator_ghost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='identity.anonymousprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ghost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes_cast', to='identity.anonymousprofile')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='workspace.note')),
            ],
            options={
                'unique_together': {('note', 'ghost')},
            },
        ),
    ]
