# Generated by Django 5.2.10 on 2026-02-14 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_remove_anonymousprofile_last_active'),
        ('workspace', '0002_boardinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='workspace.board')),
                ('ghost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.anonymousprofile')),
            ],
            options={
                'unique_together': {('board', 'ghost')},
            },
        ),
    ]
